const fs = require('fs');

function removeDark(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');
  let original = content;

  // matches 'dark:' followed by any non-space, non-quote character
  content = content.replace(/\bdark:[^\s"'\`]+/g, '');
  
  // Also clean up any double spaces generated by the removal
  content = content.replace(/ \+/g, ' +');
  content = content.replace(/" \+/g, '"+');
  content = content.replace(/  +/g, ' '); 
  content = content.replace(/ "/g, '"');
  content = content.replace(/" /g, '"');

  if (content !== original) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Removed dark classes from ${filePath}`);
  }
}

removeDark('./src/pages/Home.tsx');
removeDark('./src/components/ExtraThemes.tsx');
console.log('Done');
